
public class StringManager extends javax.swing.JFrame {

    /**
     * Creates new form StringManager
     */
        public StringManager() {
        initComponents();
        setLocationRelativeTo(null);
        botonmostrar.setEnabled(false);
        botonreiniciar.setEnabled(false);

    }

    public void habilitar() {

        if (!txtnombre.getText().isEmpty()) {

            botonmostrar.setEnabled(true);

        } else {
            botonmostrar.setEnabled(false);
        }

        if (!txtnombre.getText().isEmpty()) {

            botonreiniciar.setEnabled(true);

        } else {
            botonreiniciar.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yourname = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        botonespañol = new javax.swing.JButton();
        botoningles = new javax.swing.JButton();
        idioma = new javax.swing.JButton();
        botonreiniciar = new javax.swing.JButton();
        botonmostrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        yournameis = new javax.swing.JLabel();
        sunombre = new javax.swing.JLabel();
        yournamemay = new javax.swing.JLabel();
        yournamemin = new javax.swing.JLabel();
        nommayus = new javax.swing.JLabel();
        nomminus = new javax.swing.JLabel();
        totalcarac = new javax.swing.JLabel();
        buscarcarac = new javax.swing.JButton();
        contcaracteres = new javax.swing.JLabel();
        inicial = new javax.swing.JLabel();
        coninicial = new javax.swing.JLabel();
        buscadorletras = new javax.swing.JLabel();
        escribelo = new javax.swing.JLabel();
        ponernumero = new javax.swing.JTextField();
        botonmay = new javax.swing.JButton();
        botonmin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        posicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String manager");
        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(412, 600));
        setResizable(false);

        yourname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        yourname.setText("Write your name:");

        txtnombre.setBackground(new java.awt.Color(204, 255, 255));
        txtnombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        botonespañol.setBackground(new java.awt.Color(255, 204, 204));
        botonespañol.setForeground(new java.awt.Color(51, 51, 51));
        botonespañol.setText("SPANISH");
        botonespañol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonespañol.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                botonespañolStateChanged(evt);
            }
        });
        botonespañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonespañolActionPerformed(evt);
            }
        });
        botonespañol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botonespañolKeyTyped(evt);
            }
        });

        botoningles.setBackground(new java.awt.Color(255, 204, 204));
        botoningles.setText("ENGLISH");
        botoningles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botoningles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoninglesMouseClicked(evt);
            }
        });
        botoningles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninglesActionPerformed(evt);
            }
        });
        botoningles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botoninglesKeyPressed(evt);
            }
        });

        idioma.setBackground(new java.awt.Color(255, 153, 153));
        idioma.setText("Select  Language");
        idioma.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        idioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(yourname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idioma, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(botoningles, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonespañol, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonespañol)
                    .addComponent(botoningles)
                    .addComponent(idioma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        yourname.getAccessibleContext().setAccessibleDescription("");

        botonreiniciar.setBackground(new java.awt.Color(255, 0, 0));
        botonreiniciar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonreiniciar.setText("RESET");
        botonreiniciar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        botonreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonreiniciarActionPerformed(evt);
            }
        });
        botonreiniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonreiniciarKeyReleased(evt);
            }
        });

        botonmostrar.setBackground(new java.awt.Color(255, 153, 255));
        botonmostrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonmostrar.setText("SHOW");
        botonmostrar.setAutoscrolls(true);
        botonmostrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        botonmostrar.setName(""); // NOI18N
        botonmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmostrarActionPerformed(evt);
            }
        });
        botonmostrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonmostrarKeyReleased(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        yournameis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yournameis.setText("Your name is :");

        sunombre.setBackground(new java.awt.Color(255, 255, 255));
        sunombre.setText(".");

        yournamemay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yournamemay.setText("Your name in MAY :");

        yournamemin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        yournamemin.setText("Your name in MIN :");

        nommayus.setText(".");

        nomminus.setText(".");

        totalcarac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalcarac.setText("Character Total :");

        buscarcarac.setText("To find");
        buscarcarac.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buscarcarac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcaracActionPerformed(evt);
            }
        });

        contcaracteres.setText(".");

        inicial.setText(".");

        coninicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        coninicial.setText(" With initial in MAY:");

        buscadorletras.setBackground(new java.awt.Color(0, 153, 51));
        buscadorletras.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buscadorletras.setForeground(new java.awt.Color(255, 51, 51));
        buscadorletras.setText("letter finder");
        buscadorletras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        escribelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        escribelo.setText("write a number");

        ponernumero.setBackground(new java.awt.Color(153, 255, 255));
        ponernumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ponernumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponernumeroActionPerformed(evt);
            }
        });
        ponernumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ponernumeroKeyTyped(evt);
            }
        });

        botonmay.setBackground(new java.awt.Color(204, 204, 255));
        botonmay.setText("MAY");
        botonmay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmayActionPerformed(evt);
            }
        });

        botonmin.setBackground(new java.awt.Color(204, 204, 255));
        botonmin.setText("MIN");
        botonmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botonmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonminActionPerformed(evt);
            }
        });

        posicion.setFont(new java.awt.Font("Tahoma", 0, 90)); // NOI18N
        posicion.setText("?");
        posicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posicionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buscarcarac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponernumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(escribelo))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonmay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(yournameis))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(yournamemay)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sunombre, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(nommayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coninicial)
                            .addComponent(totalcarac)
                            .addComponent(yournamemin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscadorletras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(contcaracteres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yournameis)
                    .addComponent(sunombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yournamemay)
                    .addComponent(nommayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yournamemin)
                    .addComponent(nomminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalcarac)
                    .addComponent(contcaracteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coninicial))
                .addGap(18, 18, 18)
                .addComponent(buscadorletras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(escribelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ponernumero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(buscarcarac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonmay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonmostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonreiniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed

    }//GEN-LAST:event_txtnombreActionPerformed

    private void botonmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmostrarActionPerformed

        //lineas de abajoSystem.out.println("Your name is:" + txtName.getText()); 
        String yName = txtnombre.getText();
        //System.out.println("Your name is:" + yName );
        //show the answer in GUI
        sunombre.setText(yName);
        nommayus.setText(yName.toUpperCase());
        nomminus.setText(yName.toLowerCase());

        int x;
        x = txtnombre.getText().length();
        contcaracteres.setText(String.valueOf(x));

        String texto = txtnombre.getText();
        int i = 0;
        int d = 0;
        String texto2 = "";
        char letra;
        for (i = 0; i < x; i = i + 1) {
            if (i == 0) {
                d = 1;
            }
            letra = texto.charAt(i);
            if (d == 1) {
                letra = Character.toUpperCase(letra);
                d = 0;
            }
            if (letra == ' ') {
                d = 1;
            }
            texto2 = texto2 + letra;
        }
        texto = texto2;
        inicial.setText(texto);

//        char[] caracteres = texto.toCharArray();
//        caracteres[0] = Character.toUpperCase(caracteres[0]);
//        
//        // el -2 es para evitar una excepción al caernos del arreglo
//      for (i = 0; i < texto.length()- 2; i++) 
//  {
//    // Es 'palabra'
//        if (caracteres[i] == ' ' || caracteres[i] == '.' || caracteres[i] == ',')
//      // Reemplazamos
//      caracteres[i + 1] = Character.toUpperCase(caracteres[i + 1]);
//    }
//   
//        texto = new String(caracteres);
//        inicial.setText(texto);

    }//GEN-LAST:event_botonmostrarActionPerformed

    private void botonreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonreiniciarActionPerformed
        // TODO add your handling code here:

        txtnombre.setText("");
        sunombre.setText("");
        nomminus.setText("");
        nommayus.setText("");
        contcaracteres.setText("");
        ponernumero.setText("");
        inicial.setText("");
        posicion.setText("?");


    }//GEN-LAST:event_botonreiniciarActionPerformed

    private void botonespañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonespañolActionPerformed
        botonespañol.setEnabled(false);
        botoningles.setEnabled(true);

        yourname.setText("Escriba su nombre");
        yournameis.setText("Su nombre es");
        yournamemin.setText("Su nombre en MIN");
        yournamemay.setText("Su nombre en MAY");
        totalcarac.setText("Total caracteres");
        coninicial.setText("Con inicial en MAY");
        botonmostrar.setText("MOSTRAR");
        botonreiniciar.setText("REINICIAR");
        botoningles.setText("INGLES");
        botonespañol.setText("ESPAÑOL");
        idioma.setText("Seleccionar idioma");
        buscadorletras.setText("Buscador de letras");
        escribelo.setText("Escribe un numero");
        buscarcarac.setText("Buscar");

        // TODO add your handling code here:
    }//GEN-LAST:event_botonespañolActionPerformed

    private void idiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_idiomaActionPerformed

    private void botoninglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninglesActionPerformed
        botonespañol.setEnabled(true);
        botoningles.setEnabled(false);

        yourname.setText("Write your name");
        yournameis.setText("Your name is");
        yournamemin.setText("your name in MIN");
        yournamemay.setText("your name in MAY");
        totalcarac.setText("Character total");
        coninicial.setText("with initial in MAY");
        botonmostrar.setText("SHOW");
        botonreiniciar.setText("RESET");
        botoningles.setText("ENGLISH");
        botonespañol.setText("SPANISH");
        idioma.setText("Select languaje");
        buscadorletras.setText("Letter finder");
        escribelo.setText("Write a number");
        buscarcarac.setText("To find");

    }//GEN-LAST:event_botoninglesActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped

    }//GEN-LAST:event_txtnombreKeyTyped

    private void botonespañolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonespañolStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_botonespañolStateChanged

    private void ponernumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponernumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ponernumeroActionPerformed

    private void botonespañolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonespañolKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_botonespañolKeyTyped

    private void botoninglesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoninglesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoninglesKeyPressed

    private void botoninglesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninglesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botoninglesMouseClicked

    private void buscarcaracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcaracActionPerformed
        String numero = ponernumero.getText();
        String yName = txtnombre.getText();
        int num = Integer.parseInt(numero);

        String sub = yName.substring(num - 1, num);
        posicion.setText(sub.toUpperCase());

    }//GEN-LAST:event_buscarcaracActionPerformed

    private void ponernumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ponernumeroKeyTyped
        char num = evt.getKeyChar(); //esto es para validar unicamente ingreso de numeros
        if (Character.isDigit(num)) {
        } else {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_ponernumeroKeyTyped

    private void posicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_posicionKeyTyped


    }//GEN-LAST:event_posicionKeyTyped

    private void botonmayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmayActionPerformed

        botonmay.setEnabled(false);
        botonmin.setEnabled(true);

        String botonmay = posicion.getText();
        posicion.setText(botonmay.toUpperCase());


    }//GEN-LAST:event_botonmayActionPerformed

    private void botonminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonminActionPerformed

        botonmay.setEnabled(true);
        botonmin.setEnabled(false);

        String botonmin = posicion.getText();
        posicion.setText(botonmin.toLowerCase());


    }//GEN-LAST:event_botonminActionPerformed

    private void botonmostrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonmostrarKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_botonmostrarKeyReleased

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
            habilitar();
    }//GEN-LAST:event_txtnombreKeyReleased

    private void botonreiniciarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonreiniciarKeyReleased
            habilitar();
    }//GEN-LAST:event_botonreiniciarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringManager().setVisible(true);
                

            }
        });
    }
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonespañol;
    private javax.swing.JButton botoningles;
    private javax.swing.JButton botonmay;
    private javax.swing.JButton botonmin;
    private javax.swing.JButton botonmostrar;
    private javax.swing.JButton botonreiniciar;
    private javax.swing.JLabel buscadorletras;
    private javax.swing.JButton buscarcarac;
    private javax.swing.JLabel coninicial;
    private javax.swing.JLabel contcaracteres;
    private javax.swing.JLabel escribelo;
    private javax.swing.JButton idioma;
    private javax.swing.JLabel inicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nommayus;
    private javax.swing.JLabel nomminus;
    private javax.swing.JTextField ponernumero;
    private javax.swing.JLabel posicion;
    private javax.swing.JLabel sunombre;
    private javax.swing.JLabel totalcarac;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JLabel yourname;
    private javax.swing.JLabel yournameis;
    private javax.swing.JLabel yournamemay;
    private javax.swing.JLabel yournamemin;
    // End of variables declaration//GEN-END:variables

    private void StringMnager() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
